version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
     - .:/home/app/node-docker
